db:
  container_name: pg_container_mylomie
  image: postgres
  restart: always
  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: Root@123Root
    POSTGRES_DB: mylomie_db_development
  volumes:
    - mylomie_db:/home
  ports:
    - "5432:5432"
pgadmin:
  container_name: pgadmin4_container
  image: dpage/pgadmin4
  restart: always
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@admin.com
    PGADMIN_DEFAULT_PASSWORD: root
  links:
    - db
  ports:
    - "5050:80"
redis:
  container_name: redis_container
  image:  bitnami/redis:latest
  restart: always
  environment:
    REDIS_PASSWORD: redis123
  volumes:
    - redis-data:/home/redis
  ports:
    - 6379:6379
